apiVersion: argora.cloud.sap/v1alpha1
kind: IPPoolImport
metadata:
  labels:
    app.kubernetes.io/name: argora
    app.kubernetes.io/managed-by: kustomize
  name: ippoolimport-sample
spec:
  # TODO(user): Add fields here
